version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-net
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    networks:
      - redis-net
    restart: unless-stopped
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_PORT=8001

networks:
  redis-net:
    driver: bridge

volumes:
  redis_data:
  redisinsight_data: